/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.BillDAO;
import Entity.BillE;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thành Lùn PiPi
 */
public class BillGUI extends javax.swing.JFrame {

    /**
     * Creates new form BillGUI
     */
    private static int tt=0;
    private static int c=0;
    private static int lg=0;
    public BillGUI(int lg) {
        initComponents();
        this.lg=lg;
        getCB();
        LoadB();
    }

    
    public void getCB(){
        BillDAO b=new BillDAO();
        ArrayList<String> l = b.getTenxe();
        for(String n: l){
            cbbTenxe.addItem(n);
        }
    }
    public  void K(){
        tenKH.setEnabled(false);
        cbbTenxe.setEnabled(false);
        giaban.setEnabled(false);
        ngmua.setEnabled(false);
        IDC.setEnabled(false);
        maHD.setEnabled(false);
    }
    public void X(){
        tenKH.setText("");
        giaban.setText("");
        ngmua.setText("");
        IDC.setText("");
        maHD.setText("");
    }
    public void M(){
        tenKH.setEnabled(true);
        cbbTenxe.setEnabled(true);
    }
    public  void modelB(ArrayList<BillE> lC){
        tbB.removeAll();
        //LocalDateTime cr = LocalDateTime.now();
        String [] arr={"ID","ID xe","Tên xe","Tên khách hàng","Giá","Ngày mua"};
        DefaultTableModel model = new DefaultTableModel(arr,0);
        
        //model.addRow(arr);
        int i=0;
        for(BillE s: lC){
            
            i++;
            model.addRow(new Object[]{s.getId(), s.getIdC(),s.getNameC(),s.getNamKH(),s.getGiaM(),s.getNgmua()});
        }
        //JOptionPane.showMessageDialog(null, i);
        tbB.setModel(model);
    };
    public void LoadB(){
        K();
        //JOptionPane.showMessageDialog(null, "đã laod");
        ArrayList<BillE> lSale=new BillDAO().getAll();
        modelB(lSale); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tenKH = new javax.swing.JTextField();
        giaban = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maHD = new javax.swing.JTextField();
        IDC = new javax.swing.JTextField();
        ngmua = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbB = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        timIDHD = new javax.swing.JTextField();
        btnTimMa = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TimtenKH = new javax.swing.JTextField();
        timtenKH = new javax.swing.JButton();
        cbbTenxe = new javax.swing.JComboBox<>();
        ql = new javax.swing.JButton();
        themB = new javax.swing.JButton();
        luuB = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jLabel2.setText("Tên khách hàng:");

        jLabel3.setText("Tên xe:");

        jLabel4.setText("Giá bán:");

        jLabel5.setText("Mã hóa đơn:");

        jLabel6.setText("Mã xe:");

        jLabel7.setText("Ngày mua:");

        tbB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID xe", "Tên xe", "Tên khách hàng", "Giá", "Ngày mua"
            }
        ));
        tbB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbB);

        jLabel8.setText("Tìm mã HD:");

        btnTimMa.setText("Tìm mã");
        btnTimMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimMaActionPerformed(evt);
            }
        });

        jLabel9.setText("Tìm tên KH:");

        timtenKH.setText("Tìm tên");
        timtenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timtenKHActionPerformed(evt);
            }
        });

        cbbTenxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbTenxeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbbTenxeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbbTenxeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbTenxeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbbTenxeMouseReleased(evt);
            }
        });

        ql.setText("Quay lại");
        ql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlActionPerformed(evt);
            }
        });

        themB.setText("Thêm");
        themB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBActionPerformed(evt);
            }
        });

        luuB.setText("Lưu");
        luuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBActionPerformed(evt);
            }
        });

        jLabel10.setText("VNĐ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timIDHD, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimMa))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(giaban, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ngmua, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(jLabel5))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IDC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maHD, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TimtenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(timtenKH)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ql, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(luuB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(themB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(maHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cbbTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(IDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(ngmua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(giaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(themB)
                        .addGap(18, 18, 18)
                        .addComponent(luuB)))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(timIDHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimMa)
                    .addComponent(jLabel9)
                    .addComponent(TimtenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timtenKH)
                    .addComponent(ql))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý hóa đơn");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        //getCB();
    }//GEN-LAST:event_jPanel2ComponentShown

    private void tbBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBMouseClicked
        // TODO add your handling code here:
        tt=0;
        c=0;
        K();
        int r=tbB.getSelectedRow();
        
        int idHD=(int)(tbB.getValueAt(r, 0));
        int idC=(int)(tbB.getValueAt(r, 1));
        String tC=(String)(tbB.getValueAt(r, 2));
        String tKH=(String)(tbB.getValueAt(r, 3));
        double gia=(double)(tbB.getValueAt(r, 4));
        String ngm=(String)(tbB.getValueAt(r, 5));
        BillDAO b=new BillDAO();
        int idcb=idC-1;
        cbbTenxe.setSelectedIndex(idcb);
        maHD.setText(""+idHD);
        //IDC.setText(""+idc);
        giaban.setText(""+gia);
        ngmua.setText(ngm);
        IDC.setText(""+idC);
        tenKH.setText(tKH);
    }//GEN-LAST:event_tbBMouseClicked
    public void TimIDSale(int id){
        K();
        //String sql="select nv.ID, nv.Name, nv.Age, nv.Age, nv.Adress, nv.NumberPhone, nv.language from NhanVien nv where nv.ID="+id+"";
        ArrayList<BillE> lSale=new BillDAO().finByIDStaff(id);
        //JOptionPane.showMessageDialog(null, "sfdsf");
        modelB(lSale);
    }
    private void btnTimMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimMaActionPerformed
        // TODO add your handling code here:
        tt=0;
        c=0;
        if(timIDHD.getText().equals("")){
            LoadB();
        }
        else{
            int idSale=Integer.parseInt(timIDHD.getText().toString());
            TimIDSale(idSale);
        }
    }//GEN-LAST:event_btnTimMaActionPerformed

    private void qlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlActionPerformed
        // TODO add your handling code here:
        X();
        K();
        if(lg==1){
            Login l=new Login();
            l.setVisible(true);
            dispose();
        }
        else{
            Menu m= new Menu();
            m.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_qlActionPerformed
    public void TimTenSale(String ten){
        K();
        timIDHD.setText("");
        ArrayList<BillE> lSale=new BillDAO().finByNameStaff(ten);
        //JOptionPane.showMessageDialog(null, "sfdsf");
        modelB(lSale);
        //String sql="select nv.ID, nv.Name, nv.Age, nv.Age, nv.Adress, nv.NumberPhone, nv.language from NhanVien nv where nv.Name=N'"+ten+"'";
    }
    private void timtenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timtenKHActionPerformed
        // TODO add your handling code here:
        tt=0;
        c=0;
        if(TimtenKH.getText().equals("")){
            //JOptionPane.showMessageDialog(null, "đas");
            LoadB();
        }
        else{
            //JOptionPane.showMessageDialog(null, "123");
            TimTenSale(TimtenKH.getText().toString().trim());
        }
    }//GEN-LAST:event_timtenKHActionPerformed

    private void themBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBActionPerformed
        // TODO add your handling code here:
        tt=1;
        M();
        X();
        int tenxe=(int)(cbbTenxe.getSelectedIndex());
        int ic=tenxe+1;
        BillDAO b=new BillDAO();
        double gia=b.getGiaban(ic);
        giaban.setText(""+gia);
        IDC.setText(""+ic);
        //JOptionPane.showMessageDialog(null,tenxe+ "  Thêm thành công  "+ ic);
        
        
    }//GEN-LAST:event_themBActionPerformed

    private void luuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBActionPerformed
        // TODO add your handling code here:
        if(tt==1){
            String tenKH=this.tenKH.getText().toString();
            //int tenxe=(int)(cbbTenxe.getSelectedIndex());
            int i=Integer.parseInt((String)IDC.getText().toString());
            double g=Double.parseDouble((String)giaban.getText().toString());
            BillDAO b=new BillDAO();
            LocalDateTime cr = LocalDateTime.now();
            String datemua=""+cr.getDayOfMonth()+"/"+cr.getMonthValue()+"/"+cr.getYear();
            BillE be = new BillE(0, i, "", tenKH, g, datemua);
            b.addNew(be);
            LoadB();
            K();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        }
        
    }//GEN-LAST:event_luuBActionPerformed

    private void cbbTenxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbTenxeMouseClicked
        // TODO add your handling code here:
        tt=1;
        int tenxe=(int)(cbbTenxe.getSelectedIndex());
        int ic=tenxe+1;
        BillDAO b=new BillDAO();
        double gia=b.getGiaban(ic);
        giaban.setText(""+gia);
        IDC.setText(""+ic);
    }//GEN-LAST:event_cbbTenxeMouseClicked

    private void cbbTenxeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbTenxeMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbbTenxeMousePressed

    private void cbbTenxeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbTenxeMouseExited
        // TODO add your handling code here:
        tt=1;
        int tenxe=(int)(cbbTenxe.getSelectedIndex());
        int ic=tenxe+1;
        BillDAO b=new BillDAO();
        double gia=b.getGiaban(ic);
        giaban.setText(""+gia);
        IDC.setText(""+ic);
    }//GEN-LAST:event_cbbTenxeMouseExited

    private void cbbTenxeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbTenxeMouseEntered
        // TODO add your handling code here:
        tt=1;
        int tenxe=(int)(cbbTenxe.getSelectedIndex());
        int ic=tenxe+1;
        BillDAO b=new BillDAO();
        double gia=b.getGiaban(ic);
        giaban.setText(""+gia);
        IDC.setText(""+ic);
    }//GEN-LAST:event_cbbTenxeMouseEntered

    private void cbbTenxeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbTenxeMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbbTenxeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillGUI(lg).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDC;
    private javax.swing.JTextField TimtenKH;
    private javax.swing.JButton btnTimMa;
    private javax.swing.JComboBox<String> cbbTenxe;
    private javax.swing.JTextField giaban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luuB;
    private javax.swing.JTextField maHD;
    private javax.swing.JTextField ngmua;
    private javax.swing.JButton ql;
    private javax.swing.JTable tbB;
    private javax.swing.JTextField tenKH;
    private javax.swing.JButton themB;
    private javax.swing.JTextField timIDHD;
    private javax.swing.JButton timtenKH;
    // End of variables declaration//GEN-END:variables
}
